import type * as HostedUi from './index'

declare global {
  type Tone = HostedUi.Tone
  type ArtifactType = HostedUi.ArtifactType
  type ArtifactView = HostedUi.ArtifactView
  type ArtifactLike = HostedUi.ArtifactLike
  type NormalizedArtifact = HostedUi.NormalizedArtifact
  type ElementSize = HostedUi.ElementSize
  type ClipboardState = HostedUi.ClipboardState
  type FormErrors<T extends Record<string, any>> = HostedUi.FormErrors<T>
  type FormTouched<T extends Record<string, any>> = HostedUi.FormTouched<T>
  type ToastOptions = HostedUi.ToastOptions
  type ToastApi = HostedUi.ToastApi
  const h: typeof HostedUi.h
  const Fragment: typeof HostedUi.Fragment
  const useState: typeof HostedUi.useState
  const useReducer: typeof HostedUi.useReducer
  const useEffect: typeof HostedUi.useEffect
  const useLayoutEffect: typeof HostedUi.useLayoutEffect
  const useMemo: typeof HostedUi.useMemo
  const useCallback: typeof HostedUi.useCallback
  const useRef: typeof HostedUi.useRef
  const useElementSize: typeof HostedUi.useElementSize
  const useScrollIntoView: typeof HostedUi.useScrollIntoView
  const useScrollToBottom: typeof HostedUi.useScrollToBottom
  const useClipboard: typeof HostedUi.useClipboard
  const useLocalState: typeof HostedUi.useLocalState
  const useDebounce: typeof HostedUi.useDebounce
  const useDebouncedState: typeof HostedUi.useDebouncedState
  const useAsync: typeof HostedUi.useAsync
  const showToast: typeof HostedUi.showToast
  const Page: typeof HostedUi.Page
  const Card: typeof HostedUi.Card
  const Section: typeof HostedUi.Section
  const Heading: typeof HostedUi.Heading
  const Container: typeof HostedUi.Container
  const Stack: typeof HostedUi.Stack
  const Inline: typeof HostedUi.Inline
  const Grid: typeof HostedUi.Grid
  const Columns: typeof HostedUi.Columns
  const Split: typeof HostedUi.Split
  const ScrollArea: typeof HostedUi.ScrollArea
  const Text: typeof HostedUi.Text
  const Button: typeof HostedUi.Button
  const ButtonGroup: typeof HostedUi.ButtonGroup
  const StatusBadge: typeof HostedUi.StatusBadge
  const StatCard: typeof HostedUi.StatCard
  const KeyValue: typeof HostedUi.KeyValue
  const DataTable: typeof HostedUi.DataTable
  const Divider: typeof HostedUi.Divider
  const Toolbar: typeof HostedUi.Toolbar
  const ToolbarGroup: typeof HostedUi.ToolbarGroup
  const Alert: typeof HostedUi.Alert
  const EmptyState: typeof HostedUi.EmptyState
  const ErrorBoundary: typeof HostedUi.ErrorBoundary
  const Modal: typeof HostedUi.Modal
  const ConfirmDialog: typeof HostedUi.ConfirmDialog
  const Tooltip: typeof HostedUi.Tooltip
  const List: typeof HostedUi.List
  const Progress: typeof HostedUi.Progress
  const JsonView: typeof HostedUi.JsonView
  const Field: typeof HostedUi.Field
  const Input: typeof HostedUi.Input
  const PasswordInput: typeof HostedUi.PasswordInput
  const NumberInput: typeof HostedUi.NumberInput
  const Slider: typeof HostedUi.Slider
  const Select: typeof HostedUi.Select
  const RadioGroup: typeof HostedUi.RadioGroup
  const SegmentedControl: typeof HostedUi.SegmentedControl
  const Textarea: typeof HostedUi.Textarea
  const Switch: typeof HostedUi.Switch
  const Checkbox: typeof HostedUi.Checkbox
  const CheckboxGroup: typeof HostedUi.CheckboxGroup
  const Accordion: typeof HostedUi.Accordion
  const Markdown: typeof HostedUi.Markdown
  const ImageUpload: typeof HostedUi.ImageUpload
  const AudioUpload: typeof HostedUi.AudioUpload
  const VideoUpload: typeof HostedUi.VideoUpload
  const ImagePreview: typeof HostedUi.ImagePreview
  const AudioPlayer: typeof HostedUi.AudioPlayer
  const VideoPlayer: typeof HostedUi.VideoPlayer
  const Gallery: typeof HostedUi.Gallery
  const FileDownload: typeof HostedUi.FileDownload
  const TextBlock: typeof HostedUi.TextBlock
  const LogViewer: typeof HostedUi.LogViewer
  const JsonEditorLite: typeof HostedUi.JsonEditorLite
  const ArtifactRenderer: typeof HostedUi.ArtifactRenderer
  const ArtifactCard: typeof HostedUi.ArtifactCard
  const ArtifactList: typeof HostedUi.ArtifactList
  const normalizeArtifact: typeof HostedUi.normalizeArtifact
  const detectArtifactType: typeof HostedUi.detectArtifactType
  const Form: typeof HostedUi.Form
  const FormSection: typeof HostedUi.FormSection
  const FormActions: typeof HostedUi.FormActions
  const ActionButton: typeof HostedUi.ActionButton
  const RefreshButton: typeof HostedUi.RefreshButton
  const ActionForm: typeof HostedUi.ActionForm
  const AsyncBlock: typeof HostedUi.AsyncBlock
  const InlineError: typeof HostedUi.InlineError
  const CodeBlock: typeof HostedUi.CodeBlock
  const Tip: typeof HostedUi.Tip
  const Warning: typeof HostedUi.Warning
  const Steps: typeof HostedUi.Steps
  const Step: typeof HostedUi.Step
  const Tabs: typeof HostedUi.Tabs
  const useI18n: typeof HostedUi.useI18n
  const useForm: typeof HostedUi.useForm
  const useToast: typeof HostedUi.useToast
  const useConfirm: typeof HostedUi.useConfirm
}

export {}
